### ISSUE TITLE
[Enhancement] Import multiple documents in single YAML file into one KCL file with the `manifests.yaml_stream` function calling.

### ISSUE THREAD

**Issue by Peefy** [kcl-lang/kcl-go#319]
For example, the input YAML is

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: my-namespace
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: nginx
    ports:
    - containerPort: 80
```

The output KCL content is

```kcl
"""
This file was generated by the KCL auto-gen tool. DO NOT EDIT.
Editing this file might prove futile when you re-run the KCL auto-gen generate command.
"""

import manifests

items = [
    {
        apiVersion = "v1"
        kind = "Namespace"
        metadata = {
            name = "my-namespace"
        }
    }
    {
        apiVersion = "v1"
        kind = "Pod"
        metadata = {
            name = "my-pod"
        }
        spec = {
            containers = [
                {
                    name = "my-container"
                    image = "nginx"
                    ports = [
                        {
                            containerPort = 80
                        }
                    ]
                }
            ]
        }
    }
]

manifests.yaml_stream(items)
```
